name: Add New User HR Data


on:

  workflow_dispatch:

    inputs:

      newHrData:

        description: 'JSON string of the new user HR data'

        required: true


jobs:

  add-hr-data:

    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout repository
      
        uses: actions/checkout@v4

      - name: Set up Python

        uses: actions/setup-python@v4

        with:

          python-version: '3.10'


      - name: Run script to add HR data to secret

        env:

          EXISTING_HR_JSON: ${{ secrets.HR_DATA }}

          GH_TOKEN: ${{ secrets.PAT_FOR_SECRETS }}

          NEW_HR_JSON: ${{ github.event.inputs.newHrData }}

        run: |
          python scripts/add_hr_data.py
