name: Add New User HR Data


on:

  workflow_dispatch:

    inputs:

      newHrData:

        description: 'JSON string of the new user HR data'

        required: true


jobs:

  add-hr-data:

    runs-on: ubuntu-latest

    steps:

      - name: Set up Python

        uses: actions/setup-python@v4

        with:

          python-version: '3.10'


      - name: Run script to add HR data to secret

        env:

          EXISTING_HR_JSON: ${{ secrets.HR_DATA }}

          GH_TOKEN: ${{ secrets.PAT_FOR_SECRETS }}

          NEW_HR_JSON: ${{ github.event.inputs.newHrDataJson }}

        shell: bash

        run: |

          python << 'EOF'

          import os, json, subprocess

          try:

              existing_hr_str = os.environ.get('EXISTING_HR_JSON', '{}')

              existing_hr_data = json.loads(existing_hr_str)

              new_hr_str = os.environ['NEW_HR_JSON']

              new_hr_data = json.loads(new_hr_str)

              

              updated_hr_data = {**existing_hr_data, **new_hr_data}

              updated_hr_json_str = json.dumps(updated_hr_data)

              

              print('Updating HR_DATA secret...')

              subprocess.run(

                  ['gh', 'secret', 'set', 'HR_DATA', '--body', updated_hr_json_str],

                  check=True, text=True, capture_output=True

              )

              print('✅ Successfully updated HR_DATA secret.')

          except Exception as e:

              print(f'An error occurred: {e}')

              exit(1)

          EOF 
