name: Update Fitness Scores

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  # Runs on a schedule (every day at 7 AM UTC)
  schedule:
    - cron: '0 7 * * *'

jobs:
  update-scores:
    runs-on: ubuntu-latest

    steps:
      # 1. Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Run the Python script to generate scores.json
      - name: Run score update script
        env:
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          STRAVA_USERS: ${{ secrets.STRAVA_USERS }}
          HR_DATA: ${{ secrets.HR_DATA }}
        run: python update_scores.py

      # 5. DIAGNOSTIC STEP: Check if the file was created
      - name: Verify file creation
        run: ls -l

      # 6. Commit and push the generated scores.json file
      - name: Commit and push scores.json
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated daily score update"
          # CORRECTED: Only commit the scores.json file.
          file_pattern: scores.json

      # 7. If secrets were updated, update the GitHub Secret
      - name: Update STRAVA_USERS secret if changed
        # CORRECTED: This step now only depends on the existence of the temporary file.
        if: hashFiles('updated_strava_users.json') != ''
        env:
          GH_TOKEN: ${{ secrets.PAT_FOR_SECRETS }}
          GH_REPO: ${{ github.repository }}
        run: |
          gh secret set STRAVA_USERS --body "$(cat updated_strava_users.json)"


