name: Update Fitness Scores

on:
  # Schedule to run every day at 7:00 AM UTC (adjust as needed for your timezone)
  schedule:
    - cron: '0 7 * * *'
  # Allows you to run this workflow manually from the Actions tab in your repository
  workflow_dispatch:

jobs:
  update-scores:
    runs-on: ubuntu-latest
    steps:
      # 1. Checks out your repository's code so the script can run
      - name: Check out repo
        uses: actions/checkout@v4

      # 2. Sets up the Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. Installs the dependencies from your requirements.txt file
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Runs the score update script.
      #    It securely passes your GitHub Secrets as environment variables.
      - name: Run score update script
        run: python update_scores.py
        env:
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          STRAVA_USERS: ${{ secrets.STRAVA_USERS }}
          HR_DATA: ${{ secrets.HR_DATA }}

      # 5. Commits the updated scores.json file back to your repository.
      #    This is what makes the updated data visible to your website.
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated: Update fitness scores"
          file_pattern: "scores.json"


